 # <h1><center>Fall 2020 - DATS 6103 - Project 1 - Meron Metaferia </center></h1>

<h1><center><font size="4">Military Expenditure Analysis of 10 Countries Across different Continents</font></center></h1>

# Introduction

Some intro sentences and list of countries for analysis

<font size="3">**Targets for the Analysis**</font>

the 4 questions asked

<font size="3">**Data Source**</font>

World Bank       
SIPIRI               include links    
Iran 2018 and 2019 GDP data Konema

<font size="4">**1. Importing Packages**</font>

In [141]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')


import matplotlib.pyplot as plt
%matplotlib inline

from plotly.offline import iplot
import plotly as py
import plotly.tools as tls
import cufflinks as cf

import matplotlib.gridspec as gridspec
import plotly.graph_objs as go

**1.a. Reading GDP, Military, and Population Excel Data**

In [2]:
GDP = pd.ExcelFile('Data/GDP.xlsx')

G_tot_dol = pd.read_excel('Data/GDP.xlsx', sheet_name = 'GDP-Current-US', skiprows = 4) #Total GDP in Current US $
#G_tot_LCU = pd.read_excel('Data/GDP.xlsx', sheet_name = 'GDP-Current-LCU', skiprows = 4) #Total GDP in Local Currency(LCU) 
G_pC_dol = pd.read_excel('Data/GDP.xlsx', sheet_name = 'GDP-PerCapita-Current-US', skiprows = 4) #PerCapita GDP in US $
#G_pC_LCU = pd.read_excel('Data/GDP.xlsx', sheet_name = 'GDP-PerCapita-Current-LCU', skiprows = 4) #PerCapita GDP in Local Currency(LCU)

In [3]:
Military = pd.ExcelFile('Data/Military-C.xlsx')

M_tot_dol = pd.read_excel('Data/Military-C.xlsx', sheet_name ='Current-USD', skiprows = 3) #Total Military Expenditure in Current US $
#M_tot_LCU = pd.read_excel('Data/Military-C.xlsx', sheet_name ='Current-LCU', skiprows = 4) #Total Military Expenditure in Local Currency 
M_PCap = pd.read_excel('Data/Military-C.xlsx', sheet_name ='PerCapita', skiprows = 4) #Military Expenditure PerCapita in US $
share_GDP = pd.read_excel('Data/Military-C.xlsx', sheet_name ='Share of GDP', skiprows = 3)
#perCapita_LCU = pd.read_excel(xls, 'GDP-PerCapita-Current-LCU') #PerCapita GDP in Local Currency

In [121]:
Pop_data = pd.ExcelFile('Data/Pop.xls')

Pop = pd.read_excel('Data/Pop.xls', sheet_name ='Pop_Data', skiprows = 4) #Population Data

In [120]:
#to get an idea of what the dataset looks like

share_GDP.head()

,Country Name,Unnamed: 1,1949,1950,1951,1952,1953,1954,1955,1956,1957,1958,1959,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Africa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,North Africa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Algeria,NaN,xxx,xxx,xxx,xxx,xxx,xxx,xxx,xxx,xxx,xxx,xxx,xxx,xxx,. .,0.0251149,0.0349645,0.0341864,0.0351259,0.030191,0.0261473,0.0238687,0.0213054,0.0208759,0.0179584,0.0168816,0.0195767,0.0213109,0.0270172,0.0224195,0.0237523,0.021387,0.0210206,0.0181805,0.020631,0.0195121,0.0175512,0.0164371,0.0178721,0.0185638,0.017497,0.0154012,0.0146107,0.0121083,0.0214013,0.0250563,0.0314643,0.0293503,0.0309409,0.036374,0.0396567,0.0375508,0.0343339,0.038207,0.0370083,0.0325121,0.0328388,0.0283418,0.0264381,0.0292332,0.0302475,0.0384851,0.0351801,0.0432571,0.0446108,0.0484451,0.0554848,0.0627024,0.0638111,0.0601425,0.0551456,0.0600952
3,Libya,NaN,xxx,xxx,. .,. .,. .,. .,. .,. .,. .,. .,. .,0.01592,0.0185507,0.0310417,0.0240794,0.0184375,0.0185714,0.0291492,0.0336095,0.0285595,0.0376289,0.0607293,0.0532268,0.0370968,0.0398486,0.0329127,0.0225397,0.0196862,0.0246399,0.0379923,0.0322075,0.0292236,0.0175511,0.0224053,. .,. .,. .,. .,. .,. .,. .,. .,. .,. .,. .,. .,. .,. .,0.0407803,0.0529744,0.0378386,0.0314686,0.0241351,0.0206924,0.0207205,0.0207107,0.0152811,0.0112034,0.00946678,0.0148985,. .,. .,. .,0.037456,0.0763928,0.154796,. .,. .,. .,. .,. .
4,Morocco,NaN,xxx,xxx,xxx,xxx,xxx,xxx,xxx,0.0118065,0.01759,0.0214198,0.0246973,0.0231573,0.0270243,0.0256591,0.0319562,0.0283587,0.0242933,0.0267757,0.0261765,0.0300457,0.0239022,0.0231601,0.0262862,0.0284392,0.030618,0.0314583,0.0460291,0.0622043,0.0661977,0.0583681,0.0563346,0.0594007,0.0638459,0.0622087,0.0450566,0.0401819,0.0539044,0.0430446,0.0436931,0.0412852,0.0439292,0.0414883,0.0414284,0.0429805,0.0465557,0.0449382,0.0434741,0.0394909,0.0419266,0.0345633,0.0290046,0.0221096,0.0372614,0.0349179,0.0349421,0.0324947,0.03258,0.031098,0.0304695,0.031835,0.0328865,0.033908,0.032975,0.0346275,0.0380578,0.0367786,0.0323015,0.0321953,0.0319307,0.0312841,0.0309449

<font size="4">**2. Data Cleaning**</font>

**2.a. Selecting Specific Years and Countries**

In [99]:
#A function using column selection method 

def year(df):
    
    ''' Function to select years 2011-2019 
        for the dataframes that were imported above'''
    
    Selected = df[['Country Name', 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019]]
    return Selected

In [100]:
#applying the function above to each of the dfs

G_abs_y = year(G_tot_dol)
#df_GLCU = year(G_tot_LCU)
G_perCap_y = year(G_pC_dol)
#df_GpCLCU = year(G_pC_LCU)
M_abs_y = year(M_tot_dol)
#df_MLCU = year(M_tot_LCU)
M_perCap_y = year(M_PCap)
share_GDP_y = year(share_GDP)
Pop_y = year(Pop)

In [101]:
#checking if selection has been applied

share_GDP_y.head()

,Country Name,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Africa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,North Africa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Algeria,0.0432571,0.0446108,0.0484451,0.0554848,0.0627024,0.0638111,0.0601425,0.0551456,0.0600952
3,Libya,. .,0.037456,0.0763928,0.154796,. .,. .,. .,. .,. .
4,Morocco,0.032975,0.0346275,0.0380578,0.0367786,0.0323015,0.0321953,0.0319307,0.0312841,0.0309449

In [103]:
#isin() conditional function to select the 10 countries
#sort alphabetically by country name for ease of joining the df later

def countries(df):
    
    '''Function to select the 10 countries that are 
        listed under Introduction and do sort by Country Name.'''
    
    Selected = df[df["Country Name"].isin(['China', 'Russia', 'Germany', 'United Kingdom', 'France', 'Italy', 'Iran', 'Saudi Arabia', 'Korea, South', 'Israel'])]
    Selected.sort_values(by = 'Country Name', inplace=True)
    return Selected

In [104]:
#applying the function above to each dfs
G_abs = countries(G_abs_y)
G_Pcap = countries(G_perCap_y)
M_abs = countries(M_abs_y)
M_Pcap = countries(M_perCap_y)
Pop_d = countries(Pop_y)
M_share_G = countries(share_GDP_y)

In [105]:
#Checking if country selection has been applied

M_abs

,Country Name,2011,2012,2013,2014,2015,2016,2017,2018,2019
92,China,137967,157390,179880,200772,214471,216404,228466,253492,261082
159,France,54120.9,50216.5,52001.5,53134.8,45647.5,47370.6,49195.7,51409.8,50118.9
160,Germany,46765.5,44470.3,44865.7,44216.1,37020.1,39724.9,42365.8,46511.6,49276.8
177,Iran,14277.7,16494,11997.2,9901.11,10588.8,12264,13931.2,11230.9,12623.2
179,Israel,15163.2,14600.7,16324.8,17810,16516.8,17488.2,19434.1,19759.2,20464.9
164,Italy,33828.8,29781,29957.4,27701,22180.8,25033,26447.9,27807.5,26790.4
95,"Korea, South",30991.7,31951.8,34311.2,37552.3,36570.8,36885.3,39170.7,43070,43890.9
150,Russia,70237.5,81469.4,88352.9,84696.5,66418.3,69245.3,66527.3,61387.5,65102.6
185,Saudi Arabia,48530.9,56497.9,67020,80762.4,87185.9,63672.8,70400,74400,61866.7
173,United Kingdom,60270.4,58495.7,56861.8,59182.9,53862.2,48118.9,46433.3,49892.1,48650.4

**2.b Checking for any NaN values in the selected df**

In [106]:
#Check if there are NaN values in the df
G_abs.isnull().values.any()

False

In [107]:
#Check if there are NaN values in the df
G_Pcap.isnull().values.any()

False

In [108]:
#Check if there are NaN values in the df
M_abs.isnull().values.any()

False

In [109]:
#Check if there are NaN values in the df
M_Pcap.isnull().values.any()

False

In [110]:
#Check if there are NaN values in the df
Pop_d.isnull().values.any()

False

In [111]:
#Check if there are NaN values in the df
M_share_G.isnull().values.any()

False

**2.c. Rearranging Df for Ease of Analysis and Joining**

In [112]:
#using melt function to format df where country name will be the identifier variable and the dollar amount, %, Pop. data on a given year will be the measured values

g_abs = G_abs.melt(['Country Name'], var_name = 'Year', value_name = 'GDP_abs')
g_Pcap = G_Pcap.melt(['Country Name'], var_name = 'Year', value_name = 'GDP_Per_Capita')
m_abs = M_abs.melt(['Country Name'], var_name = 'Year', value_name = 'Military_Expenditure')
m_Pcap= M_Pcap.melt(['Country Name'], var_name = 'Year', value_name = 'Per_Capita_Military_Expenditure')
m_P_g = M_share_G.melt(['Country Name'], var_name = 'Year', value_name = 'Share_of_GDP')
POP = Pop_d.melt(['Country Name'], var_name = 'Year', value_name = 'Population')

POP

      Country Name  Year    Population
0            China  2011  1.344130e+09
1           France  2011  6.534278e+07
2          Germany  2011  8.027498e+07
3             Iran  2011  7.463496e+07
4           Israel  2011  7.765800e+06
5            Italy  2011  5.937945e+07
6     Korea, South  2011  4.993664e+07
7           Russia  2011  1.429609e+08
8     Saudi Arabia  2011  2.826768e+07
9   United Kingdom  2011  6.325881e+07
10           China  2012  1.350695e+09
11          France  2012  6.565981e+07
12         Germany  2012  8.042582e+07
13            Iran  2012  7.553986e+07
14          Israel  2012  7.910500e+06
15           Italy  2012  5.953972e+07
16    Korea, South  2012  5.019985e+07
17          Russia  2012  1.432017e+08
18    Saudi Arabia  2012  2.915519e+07
19  United Kingdom  2012  6.370022e+07
20           China  2013  1.357380e+09
21          France  2013  6.599869e+07
22         Germany  2013  8.064560e+07
23            Iran  2013  7.648194e+07
24          Israel  2013  8.059500e+06
25           Italy  2013  6.023395e+07
26    Korea, South  2013  5.042889e+07
27          Russia  2013  1.435070e+08
28    Saudi Arabia  2013  3.005252e+07
29  United Kingdom  2013  6.412827e+07
30           China  2014  1.364270e+09
31          France  2014  6.631207e+07
32         Germany  2014  8.098250e+07
33            Iran  2014  7.746575e+07
34          Israel  2014  8.215700e+06
35           Italy  2014  6.078914e+07
36    Korea, South  2014  5.074666e+07
37          Russia  2014  1.438197e+08
38    Saudi Arabia  2014  3.091699e+07
39  United Kingdom  2014  6.460230e+07
40           China  2015  1.371220e+09
41          France  2015  6.654827e+07
42         Germany  2015  8.168661e+07
43            Iran  2015  7.849222e+07
44          Israel  2015  8.380100e+06
45           Italy  2015  6.073058e+07
46    Korea, South  2015  5.101495e+07
47          Russia  2015  1.440969e+08
48    Saudi Arabia  2015  3.171767e+07
49  United Kingdom  2015  6.511622e+07
50           China  2016  1.378665e+09
51          France  2016  6.672410e+07
52         Germany  2016  8.234867e+07
53            Iran  2016  7.956402e+07
54          Israel  2016  8.546000e+06
55           Italy  2016  6.062750e+07
56    Korea, South  2016  5.121780e+07
57          Russia  2016  1.443424e+08
58    Saudi Arabia  2016  3.244257e+07
59  United Kingdom  2016  6.561159e+07
60           China  2017  1.386395e+09
61          France  2017  6.686438e+07
62         Germany  2017  8.265700e+07
63            Iran  2017  8.067395e+07
64          Israel  2017  8.713300e+06
65           Italy  2017  6.053671e+07
66    Korea, South  2017  5.136191e+07
67          Russia  2017  1.444967e+08
68    Saudi Arabia  2017  3.309915e+07
69  United Kingdom  2017  6.605886e+07
70           China  2018  1.392730e+09
71          France  2018  6.696591e+07
72         Germany  2018  8.290578e+07
73            Iran  2018  8.180027e+07
74          Israel  2018  8.882800e+06
75           Italy  2018  6.042176e+07
76    Korea, South  2018  5.160663e+07
77          Russia  2018  1.444779e+08
78    Saudi Arabia  2018  3.369995e+07
79  United Kingdom  2018  6.646034e+07
80           China  2019  1.397715e+09
81          France  2019  6.705989e+07
82         Germany  2019  8.313280e+07
83            Iran  2019  8.291391e+07
84          Israel  2019  9.053300e+06
85           Italy  2019  6.029740e+07
86    Korea, South  2019  5.170910e+07
87          Russia  2019  1.443735e+08
88    Saudi Arabia  2019  3.426853e+07
89  United Kingdom  2019  6.683440e+07

**2.d.Converting GDP_abs and Military_abs values to correct USD dollar Values**

In [113]:
#From observing the G_abs and M_abs value we see that the value amounts in dollars are not in consistent number units
# GDP_abs --> convert the values to trillion by dividing the GDP_abs series by (10^12)
#pandas series.apply function for conversion on each row value

g_abs['GDP_Absolute(USD trillions)'] = g_abs['GDP_abs'].apply(lambda x: x/1_000_000_000_000)
g_abs

      Country Name  Year       GDP_abs  GDP_Absolute(USD trillions)
0            China  2011  7.551500e+12                     7.551500
1           France  2011  2.861408e+12                     2.861408
2          Germany  2011  3.744409e+12                     3.744409
3             Iran  2011  5.807649e+11                     0.580765
4           Israel  2011  2.614686e+11                     0.261469
5            Italy  2011  2.291991e+12                     2.291991
6     Korea, South  2011  1.253223e+12                     1.253223
7           Russia  2011  2.045926e+12                     2.045926
8     Saudi Arabia  2011  6.712388e+11                     0.671239
9   United Kingdom  2011  2.659310e+12                     2.659310
10           China  2012  8.532231e+12                     8.532231
11          France  2012  2.683825e+12                     2.683825
12         Germany  2012  3.527345e+12                     3.527345
13            Iran  2012  5.988685e+11                     0.598868
14          Israel  2012  2.571801e+11                     0.257180
15           Italy  2012  2.087077e+12                     2.087077
16    Korea, South  2012  1.278428e+12                     1.278428
17          Russia  2012  2.208296e+12                     2.208296
18    Saudi Arabia  2012  7.359748e+11                     0.735975
19  United Kingdom  2012  2.704888e+12                     2.704888
20           China  2013  9.570406e+12                     9.570406
21          France  2013  2.811078e+12                     2.811078
22         Germany  2013  3.732743e+12                     3.732743
23            Iran  2013  4.602931e+11                     0.460293
24          Israel  2013  2.926362e+11                     0.292636
25           Italy  2013  2.141315e+12                     2.141315
26    Korea, South  2013  1.370795e+12                     1.370795
27          Russia  2013  2.292473e+12                     2.292473
28    Saudi Arabia  2013  7.466471e+11                     0.746647
29  United Kingdom  2013  2.786023e+12                     2.786023
30           China  2014  1.047568e+13                    10.475683
31          France  2014  2.852166e+12                     2.852166
32         Germany  2014  3.883920e+12                     3.883920
33            Iran  2014  4.326870e+11                     0.432687
34          Israel  2014  3.095585e+11                     0.309558
35           Italy  2014  2.159134e+12                     2.159134
36    Korea, South  2014  1.484318e+12                     1.484318
37          Russia  2014  2.059242e+12                     2.059242
38    Saudi Arabia  2014  7.563503e+11                     0.756350
39  United Kingdom  2014  3.063803e+12                     3.063803
40           China  2015  1.106155e+13                    11.061553
41          France  2015  2.438208e+12                     2.438208
42         Germany  2015  3.360550e+12                     3.360550
43            Iran  2015  3.849515e+11                     0.384951
44          Israel  2015  2.998131e+11                     0.299813
45           Italy  2015  1.835899e+12                     1.835899
46    Korea, South  2015  1.465773e+12                     1.465773
47          Russia  2015  1.363481e+12                     1.363481
48    Saudi Arabia  2015  6.542699e+11                     0.654270
49  United Kingdom  2015  2.928591e+12                     2.928591
50           China  2016  1.123328e+13                    11.233277
51          France  2016  2.471286e+12                     2.471286
52         Germany  2016  3.466790e+12                     3.466790
53            Iran  2016  4.179836e+11                     0.417984
54          Israel  2016  3.189506e+11                     0.318951
55           Italy  2016  1.875797e+12                     1.875797
56    Korea, South  2016  1.500112e+12                     1.500112
57          Russia  2016  1.276787e+12                     1.276787
58    Saudi Arabia  2016  6.449355e+11                     0.644936
59  United Kingdom  2016  2.694283e+12                     2.694283
60           China  2017  1.231041e+13                    12.310409
61          France  2017  2.595151e+12                     2.595151
62         Germany  2017  3.665804e+12                     3.665804
63            Iran  2017  4.453453e+11                     0.445345
64          Israel  2017  3.532534e+11                     0.353253
65           Italy  2017  1.961796e+12                     1.961796
66    Korea, South  2017  1.623901e+12                     1.623901
67          Russia  2017  1.574199e+12                     1.574199
68    Saudi Arabia  2017  6.885861e+11                     0.688586
69  United Kingdom  2017  2.666229e+12                     2.666229
70           China  2018  1.389482e+13                    13.894817
71          France  2018  2.787864e+12                     2.787864
72         Germany  2018  3.949549e+12                     3.949549
73            Iran  2018  4.585000e+11                     0.458500
74          Israel  2018  3.705880e+11                     0.370588
75           Italy  2018  2.085764e+12                     2.085764
76    Korea, South  2018  1.720579e+12                     1.720579
77          Russia  2018  1.669583e+12                     1.669583
78    Saudi Arabia  2018  7.865218e+11                     0.786522
79  United Kingdom  2018  2.860668e+12                     2.860668
80           China  2019  1.434290e+13                    14.342903
81          France  2019  2.715518e+12                     2.715518
82         Germany  2019  3.845630e+12                     3.845630
83            Iran  2019  4.461100e+11                     0.446110
84          Israel  2019  3.950987e+11                     0.395099
85           Italy  2019  2.001244e+12                     2.001244
86    Korea, South  2019  1.642383e+12                     1.642383
87          Russia  2019  1.699877e+12                     1.699877
88    Saudi Arabia  2019  7.929668e+11                     0.792967
89  United Kingdom  2019  2.827113e+12                     2.827113

In [119]:
#dropping the GDP_abs column for ease of joining 

g_ab = g_abs.drop(['GDP_abs'], axis = 1) 
g_ab

      Country Name  Year  GDP_Absolute(USD trillions)
0            China  2011                     7.551500
1           France  2011                     2.861408
2          Germany  2011                     3.744409
3             Iran  2011                     0.580765
4           Israel  2011                     0.261469
5            Italy  2011                     2.291991
6     Korea, South  2011                     1.253223
7           Russia  2011                     2.045926
8     Saudi Arabia  2011                     0.671239
9   United Kingdom  2011                     2.659310
10           China  2012                     8.532231
11          France  2012                     2.683825
12         Germany  2012                     3.527345
13            Iran  2012                     0.598868
14          Israel  2012                     0.257180
15           Italy  2012                     2.087077
16    Korea, South  2012                     1.278428
17          Russia  2012                     2.208296
18    Saudi Arabia  2012                     0.735975
19  United Kingdom  2012                     2.704888
20           China  2013                     9.570406
21          France  2013                     2.811078
22         Germany  2013                     3.732743
23            Iran  2013                     0.460293
24          Israel  2013                     0.292636
25           Italy  2013                     2.141315
26    Korea, South  2013                     1.370795
27          Russia  2013                     2.292473
28    Saudi Arabia  2013                     0.746647
29  United Kingdom  2013                     2.786023
30           China  2014                    10.475683
31          France  2014                     2.852166
32         Germany  2014                     3.883920
33            Iran  2014                     0.432687
34          Israel  2014                     0.309558
35           Italy  2014                     2.159134
36    Korea, South  2014                     1.484318
37          Russia  2014                     2.059242
38    Saudi Arabia  2014                     0.756350
39  United Kingdom  2014                     3.063803
40           China  2015                    11.061553
41          France  2015                     2.438208
42         Germany  2015                     3.360550
43            Iran  2015                     0.384951
44          Israel  2015                     0.299813
45           Italy  2015                     1.835899
46    Korea, South  2015                     1.465773
47          Russia  2015                     1.363481
48    Saudi Arabia  2015                     0.654270
49  United Kingdom  2015                     2.928591
50           China  2016                    11.233277
51          France  2016                     2.471286
52         Germany  2016                     3.466790
53            Iran  2016                     0.417984
54          Israel  2016                     0.318951
55           Italy  2016                     1.875797
56    Korea, South  2016                     1.500112
57          Russia  2016                     1.276787
58    Saudi Arabia  2016                     0.644936
59  United Kingdom  2016                     2.694283
60           China  2017                    12.310409
61          France  2017                     2.595151
62         Germany  2017                     3.665804
63            Iran  2017                     0.445345
64          Israel  2017                     0.353253
65           Italy  2017                     1.961796
66    Korea, South  2017                     1.623901
67          Russia  2017                     1.574199
68    Saudi Arabia  2017                     0.688586
69  United Kingdom  2017                     2.666229
70           China  2018                    13.894817
71          France  2018                     2.787864
72         Germany  2018                     3.949549
73            Iran  2018                     0.458500
74          Israel  2018                     0.370588
75           Italy  2018                     2.085764
76    Korea, South  2018                     1.720579
77          Russia  2018                     1.669583
78    Saudi Arabia  2018                     0.786522
79  United Kingdom  2018                     2.860668
80           China  2019                    14.342903
81          France  2019                     2.715518
82         Germany  2019                     3.845630
83            Iran  2019                     0.446110
84          Israel  2019                     0.395099
85           Italy  2019                     2.001244
86    Korea, South  2019                     1.642383
87          Russia  2019                     1.699877
88    Saudi Arabia  2019                     0.792967
89  United Kingdom  2019                     2.827113

In [114]:
#since our Sipiri military data mentions given values are in millions for the abs_military 
## military_abs USD --> divide Military_Expenditure series by 1000 to convert to billions

m_abs['Military_Expenditure(USD billions)'] = m_abs['Military_Expenditure'].apply(lambda x: x/1000)
m_abs

,Country Name,Year,Military_Expenditure,Military_Expenditure(USD billions)
0,China,2011,137967,137.967304
1,France,2011,54120.9,54.120871
2,Germany,2011,46765.5,46.765505
3,Iran,2011,14277.7,14.277667
4,Israel,2011,15163.2,15.163228
5,Italy,2011,33828.8,33.828805
6,"Korea, South",2011,30991.7,30.991708
7,Russia,2011,70237.5,70.237524
8,Saudi Arabia,2011,48530.9,48.530933
9,United Kingdom,2011,60270.4,60.270436
10,China,2012,157390,157.390377
11,France,2012,50216.5,50.216507
12,Germany,2012,44470.3,44.470342
13,Iran,2012,16494,16.493963
14,Israel,2012,14600.7,14.600666
15,Italy,2012,29781,29.781008
16,"Korea, South",2012,31951.8,31.951761
17,Russia,2012,81469.4,81.469400
18,Saudi Arabia,2012,56497.9,56.497867
19,United Kingdom,2012,58495.7,58.495657
20,China,2013,179880,179.880451
21,France,2013,52001.5,52.001462
22,Germany,2013,44865.7,44.865692
23,Iran,2013,11997.2,11.997187
24,Israel,2013,16324.8,16.324818
25,Italy,2013,29957.4,29.957446
26,"Korea, South",2013,34311.2,34.311221
27,Russia,2013,88352.9,88.352896
28,Saudi Arabia,2013,67020,67.020000
29,United Kingdom,2013,56861.8,56.861760
30,China,2014,200772,200.772204
31,France,2014,53134.8,53.134751
32,Germany,2014,44216.1,44.216058
33,Iran,2014,9901.11,9.901105
34,Israel,2014,17810,17.810044
35,Italy,2014,27701,27.701034
36,"Korea, South",2014,37552.3,37.552299
37,Russia,2014,84696.5,84.696505
38,Saudi Arabia,2014,80762.4,80.762400
39,United Kingdom,2014,59182.9,59.182859
40,China,2015,214471,214.471496
41,France,2015,45647.5,45.647472
42,Germany,2015,37020.1,37.020073
43,Iran,2015,10588.8,10.588770
44,Israel,2015,16516.8,16.516787
45,Italy,2015,22180.8,22.180845
46,"Korea, South",2015,36570.8,36.570769
47,Russia,2015,66418.3,66.418327
48,Saudi Arabia,2015,87185.9,87.185867
49,United Kingdom,2015,53862.2,53.862185
50,China,2016,216404,216.404283
51,France,2016,47370.6,47.370590
52,Germany,2016,39724.9,39.724907
53,Iran,2016,12264,12.263957
54,Israel,2016,17488.2,17.488176
55,Italy,2016,25033,25.033028
56,"Korea, South",2016,36885.3,36.885283
57,Russia,2016,69245.3,69.245309
58,Saudi Arabia,2016,63672.8,63.672800
59,United Kingdom,2016,48118.9,48.118944
60,China,2017,228466,228.466270
61,France,2017,49195.7,49.195662
62,Germany,2017,42365.8,42.365774
63,Iran,2017,13931.2,13.931196
64,Israel,2017,19434.1,19.434130
65,Italy,2017,26447.9,26.447893
66,"Korea, South",2017,39170.7,39.170682
67,Russia,2017,66527.3,66.527304
68,Saudi Arabia,2017,70400,70.400000
69,United Kingdom,2017,46433.3,46.433303
70,China,2018,253492,253.491536
71,France,2018,51409.8,51.409813
72,Germany,2018,46511.6,46.511573
73,Iran,2018,11230.9,11.230852
74,Israel,2018,19759.2,19.759173
75,Italy,2018,27807.5,27.807514
76,"Korea, South",2018,43070,43.069973
77,Russia,2018,61387.5,61.387547
78,Saudi Arabia,2018,74400,74.400000
79,United Kingdom,2018,49892.1,49.892137
80,China,2019,261082,261.081940
81,France,2019,50118.9,50.118929
82,Germany,2019,49276.8,49.276758
83,Iran,2019,12623.2,12.623163
84,Israel,2019,20464.9,20.464927
85,Italy,2019,26790.4,26.790437
86,"Korea, South",2019,43890.9,43.890862
87,Russia,2019,65102.6,65.102570
88,Saudi Arabia,2019,61866.7,61.866667
89,United Kingdom,2019,48650.4,48.650383

In [115]:
#dropping the Military_Expenditure column for ease of joining 

m_ab = m_abs.drop(['Military_Expenditure'], axis = 1) 
m_ab

      Country Name  Year  Military_Expenditure(USD billions)
0            China  2011                          137.967304
1           France  2011                           54.120871
2          Germany  2011                           46.765505
3             Iran  2011                           14.277667
4           Israel  2011                           15.163228
5            Italy  2011                           33.828805
6     Korea, South  2011                           30.991708
7           Russia  2011                           70.237524
8     Saudi Arabia  2011                           48.530933
9   United Kingdom  2011                           60.270436
10           China  2012                          157.390377
11          France  2012                           50.216507
12         Germany  2012                           44.470342
13            Iran  2012                           16.493963
14          Israel  2012                           14.600666
15           Italy  2012                           29.781008
16    Korea, South  2012                           31.951761
17          Russia  2012                           81.469400
18    Saudi Arabia  2012                           56.497867
19  United Kingdom  2012                           58.495657
20           China  2013                          179.880451
21          France  2013                           52.001462
22         Germany  2013                           44.865692
23            Iran  2013                           11.997187
24          Israel  2013                           16.324818
25           Italy  2013                           29.957446
26    Korea, South  2013                           34.311221
27          Russia  2013                           88.352896
28    Saudi Arabia  2013                           67.020000
29  United Kingdom  2013                           56.861760
30           China  2014                          200.772204
31          France  2014                           53.134751
32         Germany  2014                           44.216058
33            Iran  2014                            9.901105
34          Israel  2014                           17.810044
35           Italy  2014                           27.701034
36    Korea, South  2014                           37.552299
37          Russia  2014                           84.696505
38    Saudi Arabia  2014                           80.762400
39  United Kingdom  2014                           59.182859
40           China  2015                          214.471496
41          France  2015                           45.647472
42         Germany  2015                           37.020073
43            Iran  2015                           10.588770
44          Israel  2015                           16.516787
45           Italy  2015                           22.180845
46    Korea, South  2015                           36.570769
47          Russia  2015                           66.418327
48    Saudi Arabia  2015                           87.185867
49  United Kingdom  2015                           53.862185
50           China  2016                          216.404283
51          France  2016                           47.370590
52         Germany  2016                           39.724907
53            Iran  2016                           12.263957
54          Israel  2016                           17.488176
55           Italy  2016                           25.033028
56    Korea, South  2016                           36.885283
57          Russia  2016                           69.245309
58    Saudi Arabia  2016                           63.672800
59  United Kingdom  2016                           48.118944
60           China  2017                          228.466270
61          France  2017                           49.195662
62         Germany  2017                           42.365774
63            Iran  2017                           13.931196
64          Israel  2017                           19.434130
65           Italy  2017                           26.447893
66    Korea, South  2017                           39.170682
67          Russia  2017                           66.527304
68    Saudi Arabia  2017                           70.400000
69  United Kingdom  2017                           46.433303
70           China  2018                          253.491536
71          France  2018                           51.409813
72         Germany  2018                           46.511573
73            Iran  2018                           11.230852
74          Israel  2018                           19.759173
75           Italy  2018                           27.807514
76    Korea, South  2018                           43.069973
77          Russia  2018                           61.387547
78    Saudi Arabia  2018                           74.400000
79  United Kingdom  2018                           49.892137
80           China  2019                          261.081940
81          France  2019                           50.118929
82         Germany  2019                           49.276758
83            Iran  2019                           12.623163
84          Israel  2019                           20.464927
85           Italy  2019                           26.790437
86    Korea, South  2019                           43.890862
87          Russia  2019                           65.102570
88    Saudi Arabia  2019                           61.866667
89  United Kingdom  2019                           48.650383

In [117]:
#change share of GDP to percentages

m_P_g['Share of GDP(%)'] = m_P_g['Share_of_GDP'].apply(lambda x: x*100)
m_P_g

    Country Name  Year Share_of_GDP  Share of GDP(%)
0          China  2011    0.0183416         1.834158
1         France  2011    0.0189141         1.891406
2        Germany  2011    0.0124894         1.248942
3           Iran  2011    0.0238163         2.381635
4         Israel  2011    0.0579375         5.793753
5          Italy  2011    0.0148614         1.486136
6   Korea, South  2011    0.0247296         2.472956
7         Russia  2011    0.0342345         3.423448
8   Saudi Arabia  2011    0.0723005         7.230053
9          China  2012    0.0183645         1.836452
10        France  2012    0.0187108         1.871081
11       Germany  2012    0.0126073         1.260732
12          Iran  2012    0.0275704         2.757036
13        Israel  2012    0.0567159         5.671590
14         Italy  2012    0.0143674         1.436737
15  Korea, South  2012     0.024993         2.499300
16        Russia  2012    0.0368597         3.685969
17  Saudi Arabia  2012     0.076766         7.676603
18         China  2013    0.0186694         1.866944
19        France  2013    0.0184988         1.849876
20       Germany  2013    0.0120195         1.201949
21          Iran  2013    0.0224453         2.244535
22        Israel  2013    0.0557319         5.573191
23         Italy  2013    0.0140613         1.406128
24  Korea, South  2013    0.0250301         2.503009
25        Russia  2013    0.0384623         3.846233
26  Saudi Arabia  2013    0.0897613         8.976128
27         China  2014    0.0190585         1.905848
28        France  2014    0.0186296         1.862961
29       Germany  2014    0.0113844         1.138439
30          Iran  2014    0.0228108         2.281079
31        Israel  2014    0.0574503         5.745029
32         Italy  2014    0.0128738         1.287383
33  Korea, South  2014    0.0252994         2.529936
34        Russia  2014    0.0410418         4.104182
35  Saudi Arabia  2014     0.106779        10.677910
36         China  2015    0.0191046         1.910457
37        France  2015    0.0187226         1.872258
38       Germany  2015    0.0110166         1.101658
39          Iran  2015    0.0276031         2.760312
40        Israel  2015    0.0549697         5.496969
41         Italy  2015    0.0121062         1.210619
42  Korea, South  2015    0.0249498         2.494981
43        Russia  2015    0.0486276         4.862758
44  Saudi Arabia  2015     0.133257        13.325672
45         China  2016    0.0193004         1.930037
46        France  2016    0.0191728         1.917282
47       Germany  2016    0.0114613         1.146134
48          Iran  2016    0.0297279         2.972793
49        Israel  2016    0.0547778         5.477778
50         Italy  2016    0.0133955         1.339545
51  Korea, South  2016    0.0245958         2.459578
52        Russia  2016    0.0545241         5.452407
53  Saudi Arabia  2016    0.0987274         9.872738
54         China  2017    0.0189603         1.896030
55        France  2017    0.0191045         1.910454
56       Germany  2017    0.0116361         1.163609
57          Iran  2017    0.0310518         3.105184
58        Israel  2017    0.0552851         5.528506
59         Italy  2017    0.0136461         1.364609
60  Korea, South  2017    0.0242149         2.421489
61        Russia  2017    0.0423341         4.233407
62  Saudi Arabia  2017     0.102238        10.223848
63         China  2018    0.0189634         1.896341
64        France  2018    0.0185101         1.851010
65       Germany  2018    0.0117828         1.178279
66          Iran  2018    0.0245625         2.456251
67        Israel  2018    0.0534483         5.344830
68         Italy  2018     0.013409         1.340900
69  Korea, South  2018    0.0250304         2.503035
70        Russia  2018    0.0372418         3.724185
71  Saudi Arabia  2018    0.0950819         9.508189
72         China  2019     0.018886         1.888598
73        France  2019    0.0185722         1.857220
74       Germany  2019     0.012795         1.279500
75          Iran  2019    0.0231212         2.312119
76        Israel  2019    0.0525765         5.257651
77         Italy  2019    0.0135141         1.351407
78  Korea, South  2019    0.0267359         2.673585
79        Russia  2019    0.0387859         3.878588
80  Saudi Arabia  2019    0.0797983         7.979833

In [118]:
#dropping Share_of_GDP column for ease of joining

mPg = m_P_g.drop(['Share_of_GDP'], axis = 1) 
mPg

    Country Name  Year  Share of GDP(%)
0          China  2011         1.834158
1         France  2011         1.891406
2        Germany  2011         1.248942
3           Iran  2011         2.381635
4         Israel  2011         5.793753
5          Italy  2011         1.486136
6   Korea, South  2011         2.472956
7         Russia  2011         3.423448
8   Saudi Arabia  2011         7.230053
9          China  2012         1.836452
10        France  2012         1.871081
11       Germany  2012         1.260732
12          Iran  2012         2.757036
13        Israel  2012         5.671590
14         Italy  2012         1.436737
15  Korea, South  2012         2.499300
16        Russia  2012         3.685969
17  Saudi Arabia  2012         7.676603
18         China  2013         1.866944
19        France  2013         1.849876
20       Germany  2013         1.201949
21          Iran  2013         2.244535
22        Israel  2013         5.573191
23         Italy  2013         1.406128
24  Korea, South  2013         2.503009
25        Russia  2013         3.846233
26  Saudi Arabia  2013         8.976128
27         China  2014         1.905848
28        France  2014         1.862961
29       Germany  2014         1.138439
30          Iran  2014         2.281079
31        Israel  2014         5.745029
32         Italy  2014         1.287383
33  Korea, South  2014         2.529936
34        Russia  2014         4.104182
35  Saudi Arabia  2014        10.677910
36         China  2015         1.910457
37        France  2015         1.872258
38       Germany  2015         1.101658
39          Iran  2015         2.760312
40        Israel  2015         5.496969
41         Italy  2015         1.210619
42  Korea, South  2015         2.494981
43        Russia  2015         4.862758
44  Saudi Arabia  2015        13.325672
45         China  2016         1.930037
46        France  2016         1.917282
47       Germany  2016         1.146134
48          Iran  2016         2.972793
49        Israel  2016         5.477778
50         Italy  2016         1.339545
51  Korea, South  2016         2.459578
52        Russia  2016         5.452407
53  Saudi Arabia  2016         9.872738
54         China  2017         1.896030
55        France  2017         1.910454
56       Germany  2017         1.163609
57          Iran  2017         3.105184
58        Israel  2017         5.528506
59         Italy  2017         1.364609
60  Korea, South  2017         2.421489
61        Russia  2017         4.233407
62  Saudi Arabia  2017        10.223848
63         China  2018         1.896341
64        France  2018         1.851010
65       Germany  2018         1.178279
66          Iran  2018         2.456251
67        Israel  2018         5.344830
68         Italy  2018         1.340900
69  Korea, South  2018         2.503035
70        Russia  2018         3.724185
71  Saudi Arabia  2018         9.508189
72         China  2019         1.888598
73        France  2019         1.857220
74       Germany  2019         1.279500
75          Iran  2019         2.312119
76        Israel  2019         5.257651
77         Italy  2019         1.351407
78  Korea, South  2019         2.673585
79        Russia  2019         3.878588
80  Saudi Arabia  2019         7.979833

In [122]:
# To be able to see the whole df after I joined and sort to check if my cleaning has been applied correctly

pd.set_option("display.max_rows", None, "display.max_columns", None)

**2.e. Merging DataFrames**

In [123]:
#merging abs_GDP and PerCapita_GDP

g_merged = pd.merge(g_ab, g_Pcap, how='left', left_on=['Country Name', 'Year'], right_on=['Country Name', 'Year'], suffixes = ['GDP_Absolute(USD trillions)','GDP_Per_Capita'])
g_merged

      Country Name  Year  GDP_Absolute(USD trillions)  GDP_Per_Capita
0            China  2011                     7.551500     5618.132491
1           France  2011                     2.861408    43790.732048
2          Germany  2011                     3.744409    46644.776028
3             Iran  2011                     0.580765     7781.406114
4           Israel  2011                     0.261469    33669.246469
5            Italy  2011                     2.291991    38599.062207
6     Korea, South  2011                     1.253223    25096.263884
7           Russia  2011                     2.045926    14311.084316
8     Saudi Arabia  2011                     0.671239    23745.801614
9   United Kingdom  2011                     2.659310    42038.572250
10           China  2012                     8.532231     6316.918863
11          France  2012                     2.683825    40874.703505
12         Germany  2012                     3.527345    43858.363055
13            Iran  2012                     0.598868     7927.846902
14          Israel  2012                     0.257180    32511.237852
15           Italy  2012                     2.087077    35053.526244
16    Korea, South  2012                     1.278428    25466.760517
17          Russia  2012                     2.208296    15420.874541
18    Saudi Arabia  2012                     0.735975    25243.358698
19  United Kingdom  2012                     2.704888    42462.771568
20           China  2013                     9.570406     7050.645920
21          France  2013                     2.811078    42592.934094
22         Germany  2013                     3.732743    46285.764069
23            Iran  2013                     0.460293     6018.324473
24          Israel  2013                     0.292636    36309.468826
25           Italy  2013                     2.141315    35549.974697
26    Korea, South  2013                     1.370795    27182.734310
27          Russia  2013                     2.292473    15974.644627
28    Saudi Arabia  2013                     0.746647    24844.744371
29  United Kingdom  2013                     2.786023    43444.533002
30           China  2014                    10.475683     7678.599432
31          France  2014                     2.852166    43011.263103
32         Germany  2014                     3.883920    47959.993274
33            Iran  2014                     0.432687     5585.526758
34          Israel  2014                     0.309558    37678.889774
35           Italy  2014                     2.159134    35518.415292
36    Korea, South  2014                     1.484318    29249.575221
37          Russia  2014                     2.059242    14095.648743
38    Saudi Arabia  2014                     0.756350    24463.903164
39  United Kingdom  2014                     3.063803    47425.607681
40           China  2015                    11.061553     8066.942424
41          France  2015                     2.438208    36638.184929
42         Germany  2015                     3.360550    41139.544569
43            Iran  2015                     0.384951     4904.326877
44          Israel  2015                     0.299813    35776.795171
45           Italy  2015                     1.835899    30230.226302
46    Korea, South  2015                     1.465773    28732.231076
47          Russia  2015                     1.363481     9313.013625
48    Saudi Arabia  2015                     0.654270    20627.932782
49  United Kingdom  2015                     2.928591    44974.831877
50           China  2016                    11.233277     8147.938148
51          France  2016                     2.471286    37037.374186
52         Germany  2016                     3.466790    42098.920445
53            Iran  2016                     0.417984     5253.424843
54          Israel  2016                     0.318951    37321.624037
55           Italy  2016                     1.875797    30939.714246
56    Korea, South  2016                     1.500112    29288.870439
57          Russia  2016                     1.276787     8704.898413
58    Saudi Arabia  2016                     0.644936    19879.297530
59  United Kingdom  2016                     2.694283    41064.133432
60           China  2017                    12.310409     8879.438149
61          France  2017                     2.595151    38812.161034
62         Germany  2017                     3.665804    44349.589655
63            Iran  2017                     0.445345     5520.310789
64          Israel  2017                     0.353253    40541.862091
65           Italy  2017                     1.961796    32406.720315
66    Korea, South  2017                     1.623901    31616.843400
67          Russia  2017                     1.574199    10720.332585
68    Saudi Arabia  2017                     0.688586    20803.742566
69  United Kingdom  2017                     2.666229    40361.417383
70           China  2018                    13.894817     9976.676822
71          France  2018                     2.787864    41631.090739
72         Germany  2018                     3.949549    47639.003441
73            Iran  2018                     0.458500     5417.000000
74          Israel  2018                     0.370588    41719.725442
75           Italy  2018                     2.085764    34520.085162
76    Korea, South  2018                     1.720579    33340.265152
77          Russia  2018                     1.669583    11370.813456
78    Saudi Arabia  2018                     0.786522    23338.963458
79  United Kingdom  2018                     2.860668    43043.227816
80           China  2019                    14.342903    10261.679128
81          France  2019                     2.715518    40493.928572
82         Germany  2019                     3.845630    46258.878290
83            Iran  2019                     0.446110     5506.000000
84          Israel  2019                     0.395099    43641.397736
85           Italy  2019                     2.001244    33189.565799
86    Korea, South  2019                     1.642383    31761.977692
87          Russia  2019                     1.699877    11584.995383
88    Saudi Arabia  2019                     0.792967    23139.798656
89  United Kingdom  2019                     2.827113    42300.267126

In [124]:
#merging abs_Mil_Exp. and PerCapita_Mil_Expe

m_merged =  pd.merge(m_ab, m_Pcap, how='left', left_on=['Country Name', 'Year'], right_on=['Country Name', 'Year'], suffixes = ['Military_Expenditure(USD billions)','Per_Capita_Military_Expenditure'])
m_merged

,Country Name,Year,Military_Expenditure(USD billions),Per_Capita_Military_Expenditure
0,China,2011,137.967304,137967
1,France,2011,54.120871,54120.9
2,Germany,2011,46.765505,46765.5
3,Iran,2011,14.277667,14277.7
4,Israel,2011,15.163228,15163.2
5,Italy,2011,33.828805,33828.8
6,"Korea, South",2011,30.991708,30991.7
7,Russia,2011,70.237524,70237.5
8,Saudi Arabia,2011,48.530933,48530.9
9,United Kingdom,2011,60.270436,60270.4
10,China,2012,157.390377,157390
11,France,2012,50.216507,50216.5
12,Germany,2012,44.470342,44470.3
13,Iran,2012,16.493963,16494
14,Israel,2012,14.600666,14600.7
15,Italy,2012,29.781008,29781
16,"Korea, South",2012,31.951761,31951.8
17,Russia,2012,81.469400,81469.4
18,Saudi Arabia,2012,56.497867,56497.9
19,United Kingdom,2012,58.495657,58495.7
20,China,2013,179.880451,179880
21,France,2013,52.001462,52001.5
22,Germany,2013,44.865692,44865.7
23,Iran,2013,11.997187,11997.2
24,Israel,2013,16.324818,16324.8
25,Italy,2013,29.957446,29957.4
26,"Korea, South",2013,34.311221,34311.2
27,Russia,2013,88.352896,88352.9
28,Saudi Arabia,2013,67.020000,67020
29,United Kingdom,2013,56.861760,56861.8
30,China,2014,200.772204,200772
31,France,2014,53.134751,53134.8
32,Germany,2014,44.216058,44216.1
33,Iran,2014,9.901105,9901.11
34,Israel,2014,17.810044,17810
35,Italy,2014,27.701034,27701
36,"Korea, South",2014,37.552299,37552.3
37,Russia,2014,84.696505,84696.5
38,Saudi Arabia,2014,80.762400,80762.4
39,United Kingdom,2014,59.182859,59182.9
40,China,2015,214.471496,214471
41,France,2015,45.647472,45647.5
42,Germany,2015,37.020073,37020.1
43,Iran,2015,10.588770,10588.8
44,Israel,2015,16.516787,16516.8
45,Italy,2015,22.180845,22180.8
46,"Korea, South",2015,36.570769,36570.8
47,Russia,2015,66.418327,66418.3
48,Saudi Arabia,2015,87.185867,87185.9
49,United Kingdom,2015,53.862185,53862.2
50,China,2016,216.404283,216404
51,France,2016,47.370590,47370.6
52,Germany,2016,39.724907,39724.9
53,Iran,2016,12.263957,12264
54,Israel,2016,17.488176,17488.2
55,Italy,2016,25.033028,25033
56,"Korea, South",2016,36.885283,36885.3
57,Russia,2016,69.245309,69245.3
58,Saudi Arabia,2016,63.672800,63672.8
59,United Kingdom,2016,48.118944,48118.9
60,China,2017,228.466270,228466
61,France,2017,49.195662,49195.7
62,Germany,2017,42.365774,42365.8
63,Iran,2017,13.931196,13931.2
64,Israel,2017,19.434130,19434.1
65,Italy,2017,26.447893,26447.9
66,"Korea, South",2017,39.170682,39170.7
67,Russia,2017,66.527304,66527.3
68,Saudi Arabia,2017,70.400000,70400
69,United Kingdom,2017,46.433303,46433.3
70,China,2018,253.491536,253492
71,France,2018,51.409813,51409.8
72,Germany,2018,46.511573,46511.6
73,Iran,2018,11.230852,11230.9
74,Israel,2018,19.759173,19759.2
75,Italy,2018,27.807514,27807.5
76,"Korea, South",2018,43.069973,43070
77,Russia,2018,61.387547,61387.5
78,Saudi Arabia,2018,74.400000,74400
79,United Kingdom,2018,49.892137,49892.1
80,China,2019,261.081940,261082
81,France,2019,50.118929,50118.9
82,Germany,2019,49.276758,49276.8
83,Iran,2019,12.623163,12623.2
84,Israel,2019,20.464927,20464.9
85,Italy,2019,26.790437,26790.4
86,"Korea, South",2019,43.890862,43890.9
87,Russia,2019,65.102570,65102.6
88,Saudi Arabia,2019,61.866667,61866.7
89,United Kingdom,2019,48.650383,48650.4

In [125]:
#merging share_of_GDP and Pop. df

mPg_Pop = pd.merge(mPg, POP, how='left', left_on=['Country Name', 'Year'], right_on=['Country Name', 'Year'], suffixes = ['Share of GDP(%)','Population'])
mPg_Pop

    Country Name  Year  Share of GDP(%)    Population
0          China  2011         1.834158  1.344130e+09
1         France  2011         1.891406  6.534278e+07
2        Germany  2011         1.248942  8.027498e+07
3           Iran  2011         2.381635  7.463496e+07
4         Israel  2011         5.793753  7.765800e+06
5          Italy  2011         1.486136  5.937945e+07
6   Korea, South  2011         2.472956  4.993664e+07
7         Russia  2011         3.423448  1.429609e+08
8   Saudi Arabia  2011         7.230053  2.826768e+07
9          China  2012         1.836452  1.350695e+09
10        France  2012         1.871081  6.565981e+07
11       Germany  2012         1.260732  8.042582e+07
12          Iran  2012         2.757036  7.553986e+07
13        Israel  2012         5.671590  7.910500e+06
14         Italy  2012         1.436737  5.953972e+07
15  Korea, South  2012         2.499300  5.019985e+07
16        Russia  2012         3.685969  1.432017e+08
17  Saudi Arabia  2012         7.676603  2.915519e+07
18         China  2013         1.866944  1.357380e+09
19        France  2013         1.849876  6.599869e+07
20       Germany  2013         1.201949  8.064560e+07
21          Iran  2013         2.244535  7.648194e+07
22        Israel  2013         5.573191  8.059500e+06
23         Italy  2013         1.406128  6.023395e+07
24  Korea, South  2013         2.503009  5.042889e+07
25        Russia  2013         3.846233  1.435070e+08
26  Saudi Arabia  2013         8.976128  3.005252e+07
27         China  2014         1.905848  1.364270e+09
28        France  2014         1.862961  6.631207e+07
29       Germany  2014         1.138439  8.098250e+07
30          Iran  2014         2.281079  7.746575e+07
31        Israel  2014         5.745029  8.215700e+06
32         Italy  2014         1.287383  6.078914e+07
33  Korea, South  2014         2.529936  5.074666e+07
34        Russia  2014         4.104182  1.438197e+08
35  Saudi Arabia  2014        10.677910  3.091699e+07
36         China  2015         1.910457  1.371220e+09
37        France  2015         1.872258  6.654827e+07
38       Germany  2015         1.101658  8.168661e+07
39          Iran  2015         2.760312  7.849222e+07
40        Israel  2015         5.496969  8.380100e+06
41         Italy  2015         1.210619  6.073058e+07
42  Korea, South  2015         2.494981  5.101495e+07
43        Russia  2015         4.862758  1.440969e+08
44  Saudi Arabia  2015        13.325672  3.171767e+07
45         China  2016         1.930037  1.378665e+09
46        France  2016         1.917282  6.672410e+07
47       Germany  2016         1.146134  8.234867e+07
48          Iran  2016         2.972793  7.956402e+07
49        Israel  2016         5.477778  8.546000e+06
50         Italy  2016         1.339545  6.062750e+07
51  Korea, South  2016         2.459578  5.121780e+07
52        Russia  2016         5.452407  1.443424e+08
53  Saudi Arabia  2016         9.872738  3.244257e+07
54         China  2017         1.896030  1.386395e+09
55        France  2017         1.910454  6.686438e+07
56       Germany  2017         1.163609  8.265700e+07
57          Iran  2017         3.105184  8.067395e+07
58        Israel  2017         5.528506  8.713300e+06
59         Italy  2017         1.364609  6.053671e+07
60  Korea, South  2017         2.421489  5.136191e+07
61        Russia  2017         4.233407  1.444967e+08
62  Saudi Arabia  2017        10.223848  3.309915e+07
63         China  2018         1.896341  1.392730e+09
64        France  2018         1.851010  6.696591e+07
65       Germany  2018         1.178279  8.290578e+07
66          Iran  2018         2.456251  8.180027e+07
67        Israel  2018         5.344830  8.882800e+06
68         Italy  2018         1.340900  6.042176e+07
69  Korea, South  2018         2.503035  5.160663e+07
70        Russia  2018         3.724185  1.444779e+08
71  Saudi Arabia  2018         9.508189  3.369995e+07
72         China  2019         1.888598  1.397715e+09
73        France  2019         1.857220  6.705989e+07
74       Germany  2019         1.279500  8.313280e+07
75          Iran  2019         2.312119  8.291391e+07
76        Israel  2019         5.257651  9.053300e+06
77         Italy  2019         1.351407  6.029740e+07
78  Korea, South  2019         2.673585  5.170910e+07
79        Russia  2019         3.878588  1.443735e+08
80  Saudi Arabia  2019         7.979833  3.426853e+07

In [126]:
#merging the 3 dfs above to give one big merged df that has all the information together

merged_full = pd.merge(pd.merge(g_merged,m_merged,on=['Country Name', 'Year']),mPg_Pop,on=['Country Name', 'Year'])
merged_full

,Country Name,Year,GDP_Absolute(USD trillions),GDP_Per_Capita,Military_Expenditure(USD billions),Per_Capita_Military_Expenditure,Share of GDP(%),Population
0,China,2011,7.551500,5618.132491,137.967304,137967,1.834158,1.344130e+09
1,France,2011,2.861408,43790.732048,54.120871,54120.9,1.891406,6.534278e+07
2,Germany,2011,3.744409,46644.776028,46.765505,46765.5,1.248942,8.027498e+07
3,Iran,2011,0.580765,7781.406114,14.277667,14277.7,2.381635,7.463496e+07
4,Israel,2011,0.261469,33669.246469,15.163228,15163.2,5.793753,7.765800e+06
5,Italy,2011,2.291991,38599.062207,33.828805,33828.8,1.486136,5.937945e+07
6,"Korea, South",2011,1.253223,25096.263884,30.991708,30991.7,2.472956,4.993664e+07
7,Russia,2011,2.045926,14311.084316,70.237524,70237.5,3.423448,1.429609e+08
8,Saudi Arabia,2011,0.671239,23745.801614,48.530933,48530.9,7.230053,2.826768e+07
9,China,2012,8.532231,6316.918863,157.390377,157390,1.836452,1.350695e+09
10,France,2012,2.683825,40874.703505,50.216507,50216.5,1.871081,6.565981e+07
11,Germany,2012,3.527345,43858.363055,44.470342,44470.3,1.260732,8.042582e+07
12,Iran,2012,0.598868,7927.846902,16.493963,16494,2.757036,7.553986e+07
13,Israel,2012,0.257180,32511.237852,14.600666,14600.7,5.671590,7.910500e+06
14,Italy,2012,2.087077,35053.526244,29.781008,29781,1.436737,5.953972e+07
15,"Korea, South",2012,1.278428,25466.760517,31.951761,31951.8,2.499300,5.019985e+07
16,Russia,2012,2.208296,15420.874541,81.469400,81469.4,3.685969,1.432017e+08
17,Saudi Arabia,2012,0.735975,25243.358698,56.497867,56497.9,7.676603,2.915519e+07
18,China,2013,9.570406,7050.645920,179.880451,179880,1.866944,1.357380e+09
19,France,2013,2.811078,42592.934094,52.001462,52001.5,1.849876,6.599869e+07
20,Germany,2013,3.732743,46285.764069,44.865692,44865.7,1.201949,8.064560e+07
21,Iran,2013,0.460293,6018.324473,11.997187,11997.2,2.244535,7.648194e+07
22,Israel,2013,0.292636,36309.468826,16.324818,16324.8,5.573191,8.059500e+06
23,Italy,2013,2.141315,35549.974697,29.957446,29957.4,1.406128,6.023395e+07
24,"Korea, South",2013,1.370795,27182.734310,34.311221,34311.2,2.503009,5.042889e+07
25,Russia,2013,2.292473,15974.644627,88.352896,88352.9,3.846233,1.435070e+08
26,Saudi Arabia,2013,0.746647,24844.744371,67.020000,67020,8.976128,3.005252e+07
27,China,2014,10.475683,7678.599432,200.772204,200772,1.905848,1.364270e+09
28,France,2014,2.852166,43011.263103,53.134751,53134.8,1.862961,6.631207e+07
29,Germany,2014,3.883920,47959.993274,44.216058,44216.1,1.138439,8.098250e+07
30,Iran,2014,0.432687,5585.526758,9.901105,9901.11,2.281079,7.746575e+07
31,Israel,2014,0.309558,37678.889774,17.810044,17810,5.745029,8.215700e+06
32,Italy,2014,2.159134,35518.415292,27.701034,27701,1.287383,6.078914e+07
33,"Korea, South",2014,1.484318,29249.575221,37.552299,37552.3,2.529936,5.074666e+07
34,Russia,2014,2.059242,14095.648743,84.696505,84696.5,4.104182,1.438197e+08
35,Saudi Arabia,2014,0.756350,24463.903164,80.762400,80762.4,10.677910,3.091699e+07
36,China,2015,11.061553,8066.942424,214.471496,214471,1.910457,1.371220e+09
37,France,2015,2.438208,36638.184929,45.647472,45647.5,1.872258,6.654827e+07
38,Germany,2015,3.360550,41139.544569,37.020073,37020.1,1.101658,8.168661e+07
39,Iran,2015,0.384951,4904.326877,10.588770,10588.8,2.760312,7.849222e+07
40,Israel,2015,0.299813,35776.795171,16.516787,16516.8,5.496969,8.380100e+06
41,Italy,2015,1.835899,30230.226302,22.180845,22180.8,1.210619,6.073058e+07
42,"Korea, South",2015,1.465773,28732.231076,36.570769,36570.8,2.494981,5.101495e+07
43,Russia,2015,1.363481,9313.013625,66.418327,66418.3,4.862758,1.440969e+08
44,Saudi Arabia,2015,0.654270,20627.932782,87.185867,87185.9,13.325672,3.171767e+07
45,China,2016,11.233277,8147.938148,216.404283,216404,1.930037,1.378665e+09
46,France,2016,2.471286,37037.374186,47.370590,47370.6,1.917282,6.672410e+07
47,Germany,2016,3.466790,42098.920445,39.724907,39724.9,1.146134,8.234867e+07
48,Iran,2016,0.417984,5253.424843,12.263957,12264,2.972793,7.956402e+07
49,Israel,2016,0.318951,37321.624037,17.488176,17488.2,5.477778,8.546000e+06
50,Italy,2016,1.875797,30939.714246,25.033028,25033,1.339545,6.062750e+07
51,"Korea, South",2016,1.500112,29288.870439,36.885283,36885.3,2.459578,5.121780e+07
52,Russia,2016,1.276787,8704.898413,69.245309,69245.3,5.452407,1.443424e+08
53,Saudi Arabia,2016,0.644936,19879.297530,63.672800,63672.8,9.872738,3.244257e+07
54,China,2017,12.310409,8879.438149,228.466270,228466,1.896030,1.386395e+09
55,France,2017,2.595151,38812.161034,49.195662,49195.7,1.910454,6.686438e+07
56,Germany,2017,3.665804,44349.589655,42.365774,42365.8,1.163609,8.265700e+07
57,Iran,2017,0.445345,5520.310789,13.931196,13931.2,3.105184,8.067395e+07
58,Israel,2017,0.353253,40541.862091,19.434130,19434.1,5.528506,8.713300e+06
59,Italy,2017,1.961796,32406.720315,26.447893,26447.9,1.364609,6.053671e+07
60,"Korea, South",2017,1.623901,31616.843400,39.170682,39170.7,2.421489,5.136191e+07
61,Russia,2017,1.574199,10720.332585,66.527304,66527.3,4.233407,1.444967e+08
62,Saudi Arabia,2017,0.688586,20803.742566,70.400000,70400,10.223848,3.309915e+07
63,China,2018,13.894817,9976.676822,253.491536,253492,1.896341,1.392730e+09
64,France,2018,2.787864,41631.090739,51.409813,51409.8,1.851010,6.696591e+07
65,Germany,2018,3.949549,47639.003441,46.511573,46511.6,1.178279,8.290578e+07
66,Iran,2018,0.458500,5417.000000,11.230852,11230.9,2.456251,8.180027e+07
67,Israel,2018,0.370588,41719.725442,19.759173,19759.2,5.344830,8.882800e+06
68,Italy,2018,2.085764,34520.085162,27.807514,27807.5,1.340900,6.042176e+07
69,"Korea, South",2018,1.720579,33340.265152,43.069973,43070,2.503035,5.160663e+07
70,Russia,2018,1.669583,11370.813456,61.387547,61387.5,3.724185,1.444779e+08
71,Saudi Arabia,2018,0.786522,23338.963458,74.400000,74400,9.508189,3.369995e+07
72,China,2019,14.342903,10261.679128,261.081940,261082,1.888598,1.397715e+09
73,France,2019,2.715518,40493.928572,50.118929,50118.9,1.857220,6.705989e+07
74,Germany,2019,3.845630,46258.878290,49.276758,49276.8,1.279500,8.313280e+07
75,Iran,2019,0.446110,5506.000000,12.623163,12623.2,2.312119,8.291391e+07
76,Israel,2019,0.395099,43641.397736,20.464927,20464.9,5.257651,9.053300e+06
77,Italy,2019,2.001244,33189.565799,26.790437,26790.4,1.351407,6.029740e+07
78,"Korea, South",2019,1.642383,31761.977692,43.890862,43890.9,2.673585,5.170910e+07
79,Russia,2019,1.699877,11584.995383,65.102570,65102.6,3.878588,1.443735e+08
80,Saudi Arabia,2019,0.792967,23139.798656,61.866667,61866.7,7.979833,3.426853e+07

In [127]:
#column renaming for title asthetics

merged_full.columns = ['Country_Name', 'Year', 'GDP_Abs(USD tril)', 'GDP_PerCapita(USD)', 'Mil_Exp(USD bil)', 'Mil_Exp_PerCapita(USD)', 'Share of GDP(%)', 'Population']

In [76]:
merged_full

,Country_Name,Year,GDP_Abs(USD tril),GDP_PerCapita(USD),Mil_Exp(USD bil),Mil_Exp_PerCapita(USD),Share of GDP(%),Population
0,China,2011,7.551500,5618.132491,137.967304,137967,1.834158,1.344130e+09
1,France,2011,2.861408,43790.732048,54.120871,54120.9,1.891406,6.534278e+07
2,Germany,2011,3.744409,46644.776028,46.765505,46765.5,1.248942,8.027498e+07
3,Iran,2011,0.580765,7781.406114,14.277667,14277.7,2.381635,7.463496e+07
4,Israel,2011,0.261469,33669.246469,15.163228,15163.2,5.793753,7.765800e+06
5,Italy,2011,2.291991,38599.062207,33.828805,33828.8,1.486136,5.937945e+07
6,"Korea, South",2011,1.253223,25096.263884,30.991708,30991.7,2.472956,4.993664e+07
7,Russia,2011,2.045926,14311.084316,70.237524,70237.5,3.423448,1.429609e+08
8,Saudi Arabia,2011,0.671239,23745.801614,48.530933,48530.9,7.230053,2.826768e+07
9,China,2012,8.532231,6316.918863,157.390377,157390,1.836452,1.350695e+09
10,France,2012,2.683825,40874.703505,50.216507,50216.5,1.871081,6.565981e+07
11,Germany,2012,3.527345,43858.363055,44.470342,44470.3,1.260732,8.042582e+07
12,Iran,2012,0.598868,7927.846902,16.493963,16494,2.757036,7.553986e+07
13,Israel,2012,0.257180,32511.237852,14.600666,14600.7,5.671590,7.910500e+06
14,Italy,2012,2.087077,35053.526244,29.781008,29781,1.436737,5.953972e+07
15,"Korea, South",2012,1.278428,25466.760517,31.951761,31951.8,2.499300,5.019985e+07
16,Russia,2012,2.208296,15420.874541,81.469400,81469.4,3.685969,1.432017e+08
17,Saudi Arabia,2012,0.735975,25243.358698,56.497867,56497.9,7.676603,2.915519e+07
18,China,2013,9.570406,7050.645920,179.880451,179880,1.866944,1.357380e+09
19,France,2013,2.811078,42592.934094,52.001462,52001.5,1.849876,6.599869e+07
20,Germany,2013,3.732743,46285.764069,44.865692,44865.7,1.201949,8.064560e+07
21,Iran,2013,0.460293,6018.324473,11.997187,11997.2,2.244535,7.648194e+07
22,Israel,2013,0.292636,36309.468826,16.324818,16324.8,5.573191,8.059500e+06
23,Italy,2013,2.141315,35549.974697,29.957446,29957.4,1.406128,6.023395e+07
24,"Korea, South",2013,1.370795,27182.734310,34.311221,34311.2,2.503009,5.042889e+07
25,Russia,2013,2.292473,15974.644627,88.352896,88352.9,3.846233,1.435070e+08
26,Saudi Arabia,2013,0.746647,24844.744371,67.020000,67020,8.976128,3.005252e+07
27,China,2014,10.475683,7678.599432,200.772204,200772,1.905848,1.364270e+09
28,France,2014,2.852166,43011.263103,53.134751,53134.8,1.862961,6.631207e+07
29,Germany,2014,3.883920,47959.993274,44.216058,44216.1,1.138439,8.098250e+07
30,Iran,2014,0.432687,5585.526758,9.901105,9901.11,2.281079,7.746575e+07
31,Israel,2014,0.309558,37678.889774,17.810044,17810,5.745029,8.215700e+06
32,Italy,2014,2.159134,35518.415292,27.701034,27701,1.287383,6.078914e+07
33,"Korea, South",2014,1.484318,29249.575221,37.552299,37552.3,2.529936,5.074666e+07
34,Russia,2014,2.059242,14095.648743,84.696505,84696.5,4.104182,1.438197e+08
35,Saudi Arabia,2014,0.756350,24463.903164,80.762400,80762.4,10.677910,3.091699e+07
36,China,2015,11.061553,8066.942424,214.471496,214471,1.910457,1.371220e+09
37,France,2015,2.438208,36638.184929,45.647472,45647.5,1.872258,6.654827e+07
38,Germany,2015,3.360550,41139.544569,37.020073,37020.1,1.101658,8.168661e+07
39,Iran,2015,0.384951,4904.326877,10.588770,10588.8,2.760312,7.849222e+07
40,Israel,2015,0.299813,35776.795171,16.516787,16516.8,5.496969,8.380100e+06
41,Italy,2015,1.835899,30230.226302,22.180845,22180.8,1.210619,6.073058e+07
42,"Korea, South",2015,1.465773,28732.231076,36.570769,36570.8,2.494981,5.101495e+07
43,Russia,2015,1.363481,9313.013625,66.418327,66418.3,4.862758,1.440969e+08
44,Saudi Arabia,2015,0.654270,20627.932782,87.185867,87185.9,13.325672,3.171767e+07
45,China,2016,11.233277,8147.938148,216.404283,216404,1.930037,1.378665e+09
46,France,2016,2.471286,37037.374186,47.370590,47370.6,1.917282,6.672410e+07
47,Germany,2016,3.466790,42098.920445,39.724907,39724.9,1.146134,8.234867e+07
48,Iran,2016,0.417984,5253.424843,12.263957,12264,2.972793,7.956402e+07
49,Israel,2016,0.318951,37321.624037,17.488176,17488.2,5.477778,8.546000e+06
50,Italy,2016,1.875797,30939.714246,25.033028,25033,1.339545,6.062750e+07
51,"Korea, South",2016,1.500112,29288.870439,36.885283,36885.3,2.459578,5.121780e+07
52,Russia,2016,1.276787,8704.898413,69.245309,69245.3,5.452407,1.443424e+08
53,Saudi Arabia,2016,0.644936,19879.297530,63.672800,63672.8,9.872738,3.244257e+07
54,China,2017,12.310409,8879.438149,228.466270,228466,1.896030,1.386395e+09
55,France,2017,2.595151,38812.161034,49.195662,49195.7,1.910454,6.686438e+07
56,Germany,2017,3.665804,44349.589655,42.365774,42365.8,1.163609,8.265700e+07
57,Iran,2017,0.445345,5520.310789,13.931196,13931.2,3.105184,8.067395e+07
58,Israel,2017,0.353253,40541.862091,19.434130,19434.1,5.528506,8.713300e+06
59,Italy,2017,1.961796,32406.720315,26.447893,26447.9,1.364609,6.053671e+07
60,"Korea, South",2017,1.623901,31616.843400,39.170682,39170.7,2.421489,5.136191e+07
61,Russia,2017,1.574199,10720.332585,66.527304,66527.3,4.233407,1.444967e+08
62,Saudi Arabia,2017,0.688586,20803.742566,70.400000,70400,10.223848,3.309915e+07
63,China,2018,13.894817,9976.676822,253.491536,253492,1.896341,1.392730e+09
64,France,2018,2.787864,41631.090739,51.409813,51409.8,1.851010,6.696591e+07
65,Germany,2018,3.949549,47639.003441,46.511573,46511.6,1.178279,8.290578e+07
66,Iran,2018,0.458500,5417.000000,11.230852,11230.9,2.456251,8.180027e+07
67,Israel,2018,0.370588,41719.725442,19.759173,19759.2,5.344830,8.882800e+06
68,Italy,2018,2.085764,34520.085162,27.807514,27807.5,1.340900,6.042176e+07
69,"Korea, South",2018,1.720579,33340.265152,43.069973,43070,2.503035,5.160663e+07
70,Russia,2018,1.669583,11370.813456,61.387547,61387.5,3.724185,1.444779e+08
71,Saudi Arabia,2018,0.786522,23338.963458,74.400000,74400,9.508189,3.369995e+07
72,China,2019,14.342903,10261.679128,261.081940,261082,1.888598,1.397715e+09
73,France,2019,2.715518,40493.928572,50.118929,50118.9,1.857220,6.705989e+07
74,Germany,2019,3.845630,46258.878290,49.276758,49276.8,1.279500,8.313280e+07
75,Iran,2019,0.446110,5506.000000,12.623163,12623.2,2.312119,8.291391e+07
76,Israel,2019,0.395099,43641.397736,20.464927,20464.9,5.257651,9.053300e+06
77,Italy,2019,2.001244,33189.565799,26.790437,26790.4,1.351407,6.029740e+07
78,"Korea, South",2019,1.642383,31761.977692,43.890862,43890.9,2.673585,5.170910e+07
79,Russia,2019,1.699877,11584.995383,65.102570,65102.6,3.878588,1.443735e+08
80,Saudi Arabia,2019,0.792967,23139.798656,61.866667,61866.7,7.979833,3.426853e+07

**2.f.Sorting the fully cleaned dataframe**

In [129]:
#To sort(group) rows by country name and year both in ascending order

merged_full.sort_values(['Country_Name', 'Year'],ascending=[True,True],inplace=True)
merged_full

,Country_Name,Year,GDP_Abs(USD tril),GDP_PerCapita(USD),Mil_Exp(USD bil),Mil_Exp_PerCapita(USD),Share of GDP(%),Population
0,China,2011,7.551500,5618.132491,137.967304,137967,1.834158,1.344130e+09
9,China,2012,8.532231,6316.918863,157.390377,157390,1.836452,1.350695e+09
18,China,2013,9.570406,7050.645920,179.880451,179880,1.866944,1.357380e+09
27,China,2014,10.475683,7678.599432,200.772204,200772,1.905848,1.364270e+09
36,China,2015,11.061553,8066.942424,214.471496,214471,1.910457,1.371220e+09
45,China,2016,11.233277,8147.938148,216.404283,216404,1.930037,1.378665e+09
54,China,2017,12.310409,8879.438149,228.466270,228466,1.896030,1.386395e+09
63,China,2018,13.894817,9976.676822,253.491536,253492,1.896341,1.392730e+09
72,China,2019,14.342903,10261.679128,261.081940,261082,1.888598,1.397715e+09
1,France,2011,2.861408,43790.732048,54.120871,54120.9,1.891406,6.534278e+07
10,France,2012,2.683825,40874.703505,50.216507,50216.5,1.871081,6.565981e+07
19,France,2013,2.811078,42592.934094,52.001462,52001.5,1.849876,6.599869e+07
28,France,2014,2.852166,43011.263103,53.134751,53134.8,1.862961,6.631207e+07
37,France,2015,2.438208,36638.184929,45.647472,45647.5,1.872258,6.654827e+07
46,France,2016,2.471286,37037.374186,47.370590,47370.6,1.917282,6.672410e+07
55,France,2017,2.595151,38812.161034,49.195662,49195.7,1.910454,6.686438e+07
64,France,2018,2.787864,41631.090739,51.409813,51409.8,1.851010,6.696591e+07
73,France,2019,2.715518,40493.928572,50.118929,50118.9,1.857220,6.705989e+07
2,Germany,2011,3.744409,46644.776028,46.765505,46765.5,1.248942,8.027498e+07
11,Germany,2012,3.527345,43858.363055,44.470342,44470.3,1.260732,8.042582e+07
20,Germany,2013,3.732743,46285.764069,44.865692,44865.7,1.201949,8.064560e+07
29,Germany,2014,3.883920,47959.993274,44.216058,44216.1,1.138439,8.098250e+07
38,Germany,2015,3.360550,41139.544569,37.020073,37020.1,1.101658,8.168661e+07
47,Germany,2016,3.466790,42098.920445,39.724907,39724.9,1.146134,8.234867e+07
56,Germany,2017,3.665804,44349.589655,42.365774,42365.8,1.163609,8.265700e+07
65,Germany,2018,3.949549,47639.003441,46.511573,46511.6,1.178279,8.290578e+07
74,Germany,2019,3.845630,46258.878290,49.276758,49276.8,1.279500,8.313280e+07
3,Iran,2011,0.580765,7781.406114,14.277667,14277.7,2.381635,7.463496e+07
12,Iran,2012,0.598868,7927.846902,16.493963,16494,2.757036,7.553986e+07
21,Iran,2013,0.460293,6018.324473,11.997187,11997.2,2.244535,7.648194e+07
30,Iran,2014,0.432687,5585.526758,9.901105,9901.11,2.281079,7.746575e+07
39,Iran,2015,0.384951,4904.326877,10.588770,10588.8,2.760312,7.849222e+07
48,Iran,2016,0.417984,5253.424843,12.263957,12264,2.972793,7.956402e+07
57,Iran,2017,0.445345,5520.310789,13.931196,13931.2,3.105184,8.067395e+07
66,Iran,2018,0.458500,5417.000000,11.230852,11230.9,2.456251,8.180027e+07
75,Iran,2019,0.446110,5506.000000,12.623163,12623.2,2.312119,8.291391e+07
4,Israel,2011,0.261469,33669.246469,15.163228,15163.2,5.793753,7.765800e+06
13,Israel,2012,0.257180,32511.237852,14.600666,14600.7,5.671590,7.910500e+06
22,Israel,2013,0.292636,36309.468826,16.324818,16324.8,5.573191,8.059500e+06
31,Israel,2014,0.309558,37678.889774,17.810044,17810,5.745029,8.215700e+06
40,Israel,2015,0.299813,35776.795171,16.516787,16516.8,5.496969,8.380100e+06
49,Israel,2016,0.318951,37321.624037,17.488176,17488.2,5.477778,8.546000e+06
58,Israel,2017,0.353253,40541.862091,19.434130,19434.1,5.528506,8.713300e+06
67,Israel,2018,0.370588,41719.725442,19.759173,19759.2,5.344830,8.882800e+06
76,Israel,2019,0.395099,43641.397736,20.464927,20464.9,5.257651,9.053300e+06
5,Italy,2011,2.291991,38599.062207,33.828805,33828.8,1.486136,5.937945e+07
14,Italy,2012,2.087077,35053.526244,29.781008,29781,1.436737,5.953972e+07
23,Italy,2013,2.141315,35549.974697,29.957446,29957.4,1.406128,6.023395e+07
32,Italy,2014,2.159134,35518.415292,27.701034,27701,1.287383,6.078914e+07
41,Italy,2015,1.835899,30230.226302,22.180845,22180.8,1.210619,6.073058e+07
50,Italy,2016,1.875797,30939.714246,25.033028,25033,1.339545,6.062750e+07
59,Italy,2017,1.961796,32406.720315,26.447893,26447.9,1.364609,6.053671e+07
68,Italy,2018,2.085764,34520.085162,27.807514,27807.5,1.340900,6.042176e+07
77,Italy,2019,2.001244,33189.565799,26.790437,26790.4,1.351407,6.029740e+07
6,"Korea, South",2011,1.253223,25096.263884,30.991708,30991.7,2.472956,4.993664e+07
15,"Korea, South",2012,1.278428,25466.760517,31.951761,31951.8,2.499300,5.019985e+07
24,"Korea, South",2013,1.370795,27182.734310,34.311221,34311.2,2.503009,5.042889e+07
33,"Korea, South",2014,1.484318,29249.575221,37.552299,37552.3,2.529936,5.074666e+07
42,"Korea, South",2015,1.465773,28732.231076,36.570769,36570.8,2.494981,5.101495e+07
51,"Korea, South",2016,1.500112,29288.870439,36.885283,36885.3,2.459578,5.121780e+07
60,"Korea, South",2017,1.623901,31616.843400,39.170682,39170.7,2.421489,5.136191e+07
69,"Korea, South",2018,1.720579,33340.265152,43.069973,43070,2.503035,5.160663e+07
78,"Korea, South",2019,1.642383,31761.977692,43.890862,43890.9,2.673585,5.170910e+07
7,Russia,2011,2.045926,14311.084316,70.237524,70237.5,3.423448,1.429609e+08
16,Russia,2012,2.208296,15420.874541,81.469400,81469.4,3.685969,1.432017e+08
25,Russia,2013,2.292473,15974.644627,88.352896,88352.9,3.846233,1.435070e+08
34,Russia,2014,2.059242,14095.648743,84.696505,84696.5,4.104182,1.438197e+08
43,Russia,2015,1.363481,9313.013625,66.418327,66418.3,4.862758,1.440969e+08
52,Russia,2016,1.276787,8704.898413,69.245309,69245.3,5.452407,1.443424e+08
61,Russia,2017,1.574199,10720.332585,66.527304,66527.3,4.233407,1.444967e+08
70,Russia,2018,1.669583,11370.813456,61.387547,61387.5,3.724185,1.444779e+08
79,Russia,2019,1.699877,11584.995383,65.102570,65102.6,3.878588,1.443735e+08
8,Saudi Arabia,2011,0.671239,23745.801614,48.530933,48530.9,7.230053,2.826768e+07
17,Saudi Arabia,2012,0.735975,25243.358698,56.497867,56497.9,7.676603,2.915519e+07
26,Saudi Arabia,2013,0.746647,24844.744371,67.020000,67020,8.976128,3.005252e+07
35,Saudi Arabia,2014,0.756350,24463.903164,80.762400,80762.4,10.677910,3.091699e+07
44,Saudi Arabia,2015,0.654270,20627.932782,87.185867,87185.9,13.325672,3.171767e+07
53,Saudi Arabia,2016,0.644936,19879.297530,63.672800,63672.8,9.872738,3.244257e+07
62,Saudi Arabia,2017,0.688586,20803.742566,70.400000,70400,10.223848,3.309915e+07
71,Saudi Arabia,2018,0.786522,23338.963458,74.400000,74400,9.508189,3.369995e+07
80,Saudi Arabia,2019,0.792967,23139.798656,61.866667,61866.7,7.979833,3.426853e+07

<font size="4">**3.Data Visualization**</font>

**3.a.Comparing the military data to the country’s GDP in abs**

(using GDP_Abs(USD tril) and g

**3.c. Overall military spending of all 10 countries**